[tool.black]
line-length = 79

[tool.poetry]
name = "pypi-playground"
version = "0.1.0"
description = ""
authors = ["kitsuyui <kitsuyui@kitsuyui.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.group.dev.dependencies]
black = "*"
pytest = "*"
isort = "*"
pyupgrade = "*"
pytest-cov = "*"
flake8 = "*"
mypy = "*"
poethepoet = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
test = "pytest"
coverage-xml = "pytest --cov=playground playground --doctest-modules --cov-report=xml"
format = [
    { cmd = "isort playground"},
    { cmd = "black playground"},
    { cmd = "pyupgrade --py37-plus playground/*.py"},
]
check = [
    { cmd = "isort --check-only --diff playground"},
    { cmd = "black --check --diff playground"},
    { cmd = "flake8 playground"},
    { cmd = "mypy playground"},
]
[tool.mypy]
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = false

[tool.mypy-tests."*"]
disallow_untyped_defs = false
warn_return_any = false
ignore_missing_imports = true
