[project]
name = "kitsuyui.hello"
dynamic = ["version"]
description = "A playground for publishing packages to PyPI"
requires-python = ">=3.8"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    {name = "Yui KITSU", email = "kitsuyui+github@kitsuyui.com"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: BSD License",
]

[project.urls]
Homepage = "https://github.com/kitsuyui/pypi-playground"

[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
package-data = { "*" = ["README.md, LICENSE", "py.typed", "*.pyi"] }

[tool.setuptools.packages.find]
where = ["src/"]
include = ["kitsuyui.hello"]

[tool.setuptools_scm]
version_file = "./src/kitsuyui/hello/_version.py"
root = "../.."

[dependency-groups]
dev = [
    "dev-shared",
]

[tool.uv.sources]
dev-shared = { workspace = true }

[tool.poe]
include = "../dev-shared/poe.tasks.toml"
