[tool.poetry]
# I use poetry as just a package manager.
# So, I only write the settings that poetry needs.
# The actual package metadata is written in setup.cfg.
# I use pypa/build for packaging.
name = "kitsuyui.hello"
version = "0.0.0"
description = ""
authors = []
packages = [{ include = "src/hello" }]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
poethepoet = "*"
setuptools-scm = "*"
build = "*"

[project]
name = "kitsuyui.hello"
dynamic = ["version"]

[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools_scm]
version_file = "./src/hello/_version.py"
root = "../../"
relative_to = "__file__"

[tool.poe.tasks]
test = "pytest"
coverage-xml = "pytest --cov=src --doctest-modules --cov-report=xml"
build = [{ cmd = "python -m build" }]
