name: octocov
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  octocov:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.14"]

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "${{ matrix.python }}"

      - name: Set up uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv python pin ${{ matrix.python }}
          uv sync
          uv run poe sync-all

      - name: Build
        run: |
          uv run poe build

      - name: Test
        run: uv run poe test

      - name: Coverage
        run: uv run poe coverage

      # See also: https://github.com/k1LoW/octocov-action
      - name: Report coverage with octocov
        uses: k1LoW/octocov-action@b3b6ee60482a667950f87553abf1df63217235d9 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config: .octocov.yml
