name: Packaging

on:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    # "released" events are emitted either when directly be released or be edited from pre-released.
    types: [prereleased, released]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  python_version: 3.13

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        targets: ['kitsuyui-animal', 'kitsuyui-content_addr', 'kitsuyui-hello']
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: ${{ env.python_version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync
          uv run poe sync-all

      - name: Build
        run: uv run poe build

      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
        if: github.event_name == 'release' && github.event.release.prerelease
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: packages/${{ matrix.targets }}/dist

      - name: Publish distribution to PyPI
        if: github.event_name == 'release' && !github.event.release.prerelease
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
        with:
          packages-dir: packages/${{ matrix.targets }}/dist
          attestations: true
