name: Packaging

on:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    # "released" events are emitted either when directly be released or be edited from pre-released.
    types: [prereleased, released]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  python_version: 3.13

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        targets: ['kitsuyui-animal', 'kitsuyui-content_addr', 'kitsuyui-hello']
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: ${{ env.python_version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync
          uv run poe sync-all

      - name: Build
        run: uv run poe build

      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247
        if: github.event_name == 'release' && github.event.release.prerelease
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: packages/${{ matrix.targets }}/dist

      - name: Publish distribution to PyPI
        if: github.event_name == 'release' && !github.event.release.prerelease
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247
        with:
          packages-dir: packages/${{ matrix.targets }}/dist
          attestations: true
