name: Test
on:
  # pull-request events are not triggered when a PR is merged
  # push events are not triggered when a PR created from a fork repository
  # So we need both to run tests on every PR and after merging
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "${{ matrix.python }}"

      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv python pin ${{ matrix.python }}
          uv sync
          uv run poe sync-all

      - parallel:
          - name: Build
            run: |
              uv run poe build

          - name: Lint
            run: uv run poe check

          - name: Check Python version
            run: |
              actual_version=$(uv run python --version)
              expected_version="Python ${{ matrix.python }}"
              if [[ "$actual_version" != *"$expected_version"* ]]; then
                echo "Expected $expected_version, but got $actual_version"
                exit 1
              fi

          - name: Test
            run: uv run poe test

      - name: Coverage
        run: uv run poe coverage
